// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SPKBultenAnaliz.DataAccess;

#nullable disable

namespace SPKBultenAnaliz.DataAccess.Migrations
{
    [DbContext(typeof(BultenDbContext))]
    [Migration("20260731090000_AddSektorSutunu")]
    partial class AddSektorSutunu
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SPKBultenAnaliz.Core.Entities.Bulten", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BultenAdi")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Durum")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasDefaultValue("Beklemede");

                    b.Property<string>("GenelYoneticiOzeti")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("KayitTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("PdfUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("YayinTarihi")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("PdfUrl")
                        .IsUnique();

                    b.HasIndex("YayinTarihi");

                    b.ToTable("Bultenler");
                });

            modelBuilder.Entity("SPKBultenAnaliz.Core.Entities.BultenAnalizSonucu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AiGerekceYorumu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("BultenId")
                        .HasColumnType("int");

                    b.Property<string>("DuyguDurumu")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("EtkiSkoru")
                        .HasColumnType("int");

                    b.Property<string>("EtkilenenUnsur")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("Sektor")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("BultenId");

                    b.HasIndex("Sektor");

                    b.ToTable("BultenAnalizSonuclari");
                });

            modelBuilder.Entity("SPKBultenAnaliz.Core.Entities.BultenMetinBlogu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BlokSiraNo")
                        .HasColumnType("int");

                    b.Property<int>("BultenId")
                        .HasColumnType("int");

                    b.Property<string>("HamMetinIcerigi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("KayitTarihi")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("BultenId", "BlokSiraNo");

                    b.ToTable("BultenMetinBloklari");
                });

            modelBuilder.Entity("SPKBultenAnaliz.Core.Entities.BultenAnalizSonucu", b =>
                {
                    b.HasOne("SPKBultenAnaliz.Core.Entities.Bulten", "Bulten")
                        .WithMany("AnalizSonuclari")
                        .HasForeignKey("BultenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bulten");
                });

            modelBuilder.Entity("SPKBultenAnaliz.Core.Entities.BultenMetinBlogu", b =>
                {
                    b.HasOne("SPKBultenAnaliz.Core.Entities.Bulten", "Bulten")
                        .WithMany("MetinBloklari")
                        .HasForeignKey("BultenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bulten");
                });

            modelBuilder.Entity("SPKBultenAnaliz.Core.Entities.Bulten", b =>
                {
                    b.Navigation("AnalizSonuclari");

                    b.Navigation("MetinBloklari");
                });
#pragma warning restore 612, 618
        }
    }
}
